# Generated by Django 2.2.6 on 2019-10-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('deliveryEstimate', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('imagePath', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('hours', models.TextField()),
            ],
        ),
    ]
