# Generated by Django 2.2.6 on 2019-10-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
