# Generated by Django 2.2.6 on 2019-10-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comments', models.TextField()),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurante')),
            ],
        ),
    ]
