# Generated by Django 2.2.6 on 2019-10-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20191019_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurantId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurante', to_field='slug'),
            preserve_default=False,
        ),
    ]
