# Generated by Django 2.2.6 on 2019-10-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20191019_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurantId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurante'),
        ),
    ]
